# Package definition for bottom

package_name: bottom
github_repo: ClementTsang/bottom
license: MIT
artifact_format: tar.gz
description: "A cross-platform graphical process/system monitor with a customizable interface"
license: MIT

# Build for all Debian suites and all supported architectures.
